default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_interaction_app_development

test:
  <<: *default
  database: book_interaction_app_test

production:
  <<: *default
  database: <%= ENV['BOOK_INTERACTION_APP_DATABASE'] %>
  username: <%= ENV['BOOK_INTERACTION_APP_DATABASE_USER'] %>
  password: <%= ENV['BOOK_INTERACTION_APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['BOOK_INTERACTION_APP_DATABASE_HOST'] %>
  port: <%= ENV['BOOK_INTERACTION_APP_DATABASE_PORT'] %>
